STEK SEGMENT PARA STACK 'ST_'
		DB 20 DUP(?)
		DB 30 DUP(?)
STEK ENDS

DSG SEGMENT PARA 'DS_'
		ARRAY DW 4, 10, 0FFFFH, 0FE01H, 255
		N DW 5
		SQRT DB 5 DUP(10)	
DSG ENDS

CSG SEGMENT PARA 'CS_'
		ASSUME CS: CSG, DS: DSG, SS: STEK
		MAIN PROC FAR
			PUSH DS
			XOR AX, AX
			PUSH AX 				; GERI DONUS'U BELIRTMEK ICIN

			MOV AX, DSG
			MOV DS, AX 				; DS'I ATAMAK ISTIYORUZ O YUZDEN
			
			MOV CX, N
			XOR SI, SI

			L1: 					; FOR DONGUSU
				MOV BX, ARRAY[SI] 	; INDEX RELATIVE
				MOV DL, 1
				XOR AX, AX
				XOR DH, DH
				L3: 
				CMP DL, 255
				JE L2		

				CMP AX, BX			; AL^2 // ARRAY[SI]
				JA L2
				ADD AX, DX
				ADD DL, 2
				JMP L3

				L2: 
				SHR SI, 1 			; SQRT DIZISI ICIN INDEX'IN SI'NIN YARISI OLMALI, SI 2'SER ARTIYOR CUNKU
				MOV AX, DX
				MOV DL, 2
				DIV DL
				DEC AL
				
				MOV SQRT[SI], AL
				SHL SI, 1			; SI DEGERINI 2 ILE GENISLET
				ADD SI, 2			
			LOOP L1



			RETF
		MAIN ENDP
CSG ENDS
		END MAIN


; KAREKOKU ASAGIYA YUVARLAYAN KODU YAZ
; ARDISIK TEK SAYILARIN TOPLAMININ BIR TAM KARE OLMASINDAN FAYDALANARAK SQRT = KOK(ARRAY)-FLOOR-

; AKIS SEMASI CIZDIKTEN SONRA YAPMAK DAHA KOLAY HALE GELIYOR