STEK SEGMENT PARA STACK 'ST_'
		DW 20 DUP(?)
STEK ENDS

DSG SEGMENT PARA 'DS_'
		ARRAY DW 9, 16, 25, 1, 0, 18, 29, 0FFFFH, 0FE01H, 255
		N DW 10
		SQRT DB 10 DUP(0)	
DSG ENDS

CSG SEGMENT PARA 'CS_'
		ASSUME CS: CSG, DS: DSG, SS: STEK
		MAIN PROC FAR
			PUSH DS
			XOR AX, AX
			PUSH AX 				; GERI DONUS'U BELIRTMEK ICIN

			MOV AX, DSG
			MOV DS, AX 				; DS'I ATAMAK ISTIYORUZ O YUZDEN
			
			MOV CX, N
			XOR SI, SI

			L1: 					; FOR DONGUSU
				MOV BX, ARRAY[SI] 	; INDEX RELATIVE
				XOR DL, DL
				L3: 
				CMP DL, 255
				JE L2
				MOV AL, DL
				MUL AL 				; AX <- AL^2
				CMP AX, BX			; AL^2 // ARRAY[SI]
				JA L2
				INC DL
				JMP L3

				L2: 
				SHR SI, 1 			; SQRT DIZISI ICIN INDEX'IN SI'NIN YARISI OLMALI, SI 2'SER ARTIYOR CUNKU
				
				MOV SQRT[SI], DL
				SHL SI, 1			; SI DEGERINI 2 ILE GENISLET
				ADD SI, 2			
			LOOP L1



			RETF
		MAIN ENDP
CSG ENDS
		END MAIN


; KAREKOKU ASAGIYA YUVARLAYAN KODU YAZ
; ARDISIK TEK SAYILARIN TOPLAMININ BIR TAM KARE OLMASINDAN FAYDALANARAK SQRT = KOK(ARRAY)-FLOOR-

; AKIS SEMASI CIZDIKTEN SONRA YAPMAK DAHA KOLAY HALE GELIYOR