STG SEGMENT PARA STACK 'ST_'
		DW 20 DUP(?)
STG ENDS

DSG SEGMENT PARA 'DS_'
		ASSDAS DB 20 DUP(2)
		WEIGHT DW 330, 190, 298 DUP(200)
		HEIGHT DB 70, 100, 298 DUP(90)
		BMI DB 300 DUP(0)
		N DW 300
		THRESH DB 3
		OVERW DW 0
DSG ENDS

CSG SEGMENT PARA 'CS_'
		ASSUME CS: CSG, DS: DSG, SS: STG
		MAIN PROC FAR
			PUSH DS
			XOR AX, AX
			PUSH AX 				; GERI DONUS'U BELIRTMEK ICIN

			MOV AX, DSG
			MOV DS, AX 				; DS'I ATAMAK ISTIYORUZ O YUZDEN
			
			LEA SI, WEIGHT			; WORD DIZI IND
			LEA DI, HEIGHT			; BYTE DIZI IND
			LEA BX, BMI				; BYTE DIZI IND
			MOV CX, N

			L1: 
				MOV AX, [SI]		;WEIGHT SIRADAKI ELEMAN
				MOV DX, 703
				MUL DX				; DX:AX <- W*703
				PUSH BX
				PUSH AX

				MOV AL, [DI]		;HEIGHT SIRADAKI ELEMAN
				MUL AL
				MOV BX, AX 			; BX = H^2
				POP AX
				DIV BX

				POP BX
				MOV [BX], AL		;BMI SIRADAKI ELEMAN
				CMP AL, THRESH
				JB L2
				INC OVERW
				L2:
								
				ADD SI, 2
				INC DI
				INC BX



			RETF
		MAIN ENDP
CSG ENDS
		END MAIN
